### ISSUE TITLE
Wrong quantity discounts when selling without VAT

### ISSUE THREAD

**Issue by elund** [thirtybees/thirtybees#264]
When - for instance - selling to customers outside EU, you should not charge VAT. 
But quantity discounts are wrong when selling without VAT, because they always include VAT.
So when checking out, prices are without VAT but quantity discount are with VAT, resulting in too much discounts to the customers.
This is a really old and known bug in PrestaShop, that would be very nice to finally get fixed.

**Comment by firstred** [comment]
Thank you. I have added the `1.0.2` label, because we want to get this solved with the next release.

**Comment by firstred** [comment]
This is caused by the fact that it tries to calculate from the total amount of tax applied to the cart (which is always `0` in those cases). From the front office it is not possible to find the original tax.

I am going to add an option on the BO tax page to select the default tax ID, so in case the original, if the tax cannot be found we can use this tax as a reference. It will be limited to just one tax, though.
![taxoptions](https://user-images.githubusercontent.com/6775736/27623201-94ea4840-5bdb-11e7-86ee-fa84dea2c8ad.png)

If you need to support more taxes, then I suggest to always enter specific price rules without tax and set the tax option to "Tax excluded". This way the catalog price rule tax will become more flexible.

**Comment by firstred** [comment]
Changes: https://github.com/thirtybees/thirtybees/commit/70692c2c1f5a44caccde3365d3bb30417656dc8a

**Comment by elund** [comment]
To test this, is it enough to copy the 2 files (classes/Product.php and controllers/admin/AdminTaxesController.php) to an existing Thirtybees 1.0.1 installation?
I tried and got not errors, but my problem was not resolved?

**Comment by firstred** [comment]
Carts and some price calculations are cached. I could only see the updated discounts after clearing all carts.

**Comment by Casper-O** [comment]
Is this the "right" solution?

The solution that this person suggested over at prestashop github seems to do the trick, without any limitations like the current work around:

https://github.com/urimarti/Prestashop/commit/cb02974cacba8457eedd54c203fc12ff1b0c8372#diff-0a7a17e9ff155e6890d7a5b01eea713c
