### ISSUE TITLE
BO password recovery doesn't work

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#568]
When entering a valid email address, it says:
`There is one error.
This account does not exist.`
And no email is being sent tp the valid email address.

I'd also suggest to enhance security by changing the notice to say in all cases, something along the lines:
"If the email address exist in our records, an email with instructions will be there shortly".

This is to prevent confirming a possible hacker which email addresses are registered and prevent brute force attacks.
Adding reCpatcha may also help. (although I normally use http auth in addition).

I'd also suggest implementing such message on the customer's email recovery request in FO, less due to hackers, but more due to competitors checking if certain customers are registered etc.

**Comment by zapps12** [comment]
I have this issue as well.
Recently lost my password and had to reset in database.

**Comment by Traumflug** [comment]
The commit noted in this thread should fix it. Thank you very much for reporting it!

**Comment by doclucas** [comment]
Thanks.
As gonssal pointed out:
"You should actually revert the entirety of the original commit. The isPasswd() function checks that a password is not too long and removing it allows malicious users to post a very big password, causing a DoS.

Check this: https://www.rapid7.com/db/modules/auxiliary/dos/http/wordpress_long_password_dos"

He is correct.

**Comment by Traumflug** [comment]
`password_verify()`, which is what thirty bees uses, is safe against timing attacks. Says https://secure.php.net/manual/en/function.password-verify.php Which means, a verification always takes the same (low) amount of resource usage, no matter how long the password is.

**Comment by doclucas** [comment]
While you were working on fixing it, I tried some of  the changes and the got the password, so it worked.
Now, when I am testing on 1.0.6, I still don't get the admin password emailed to the valid email address.

**Comment by doclucas** [comment]
I'll be happy to check this, but I am not really familiar with TB code and which file and specific variable to look for.
Could you please let me know more specifically & detailed debug instructions for this case?

Thanks

**Comment by Traumflug** [comment]
Decision whether an email gets sent is happening here: https://github.com/thirtybees/thirtybees/blob/1.0.x/controllers/admin/AdminLoginController.php#L293

One reason to not sent email is that an email was sent in the 6 hours (360 minutes) before. One can change this delay in back office -> *Administration* -> *Employees* for employees and in back office -> *Preferences* -> *Customers* for customers.

**Comment by doclucas** [comment]
odd. seems to some issue with `$nextEmailTime`, but I am not sure.
I dropped the time to 1 minute and now it works.
I think this issue can be closed for now. I will re-open it if I can reproduce and give more information.
Thanks
